# Convenient root makefile. Invokes `cmake` and then `cmake --build` as needed.
preset := x86_64-linux-debug

BUILD_ROOT = build
BUILD_DIR = $(BUILD_ROOT)/cmake-$(preset)
CMAKECACHE = $(BUILD_DIR)/CMakeCache.txt
CMAKE_ARGS = --preset $(preset) -B $(BUILD_DIR)

ifeq ($(MAKECMDGOALS),)
# If no targets were specified, synthesize a default target.
.PHONY: _default
_default: $(CMAKECACHE)
	@cmake --build $(BUILD_DIR)
else
# If targets were specified, pass them through to `cmake --build`.
.PHONY: $(MAKECMDGOALS)
$(word 1,$(MAKECMDGOALS)):: $(CMAKECACHE)
	@cmake --build $(BUILD_DIR) -t $(MAKECMDGOALS)
$(MAKECMDGOALS)::
	@#

endif

# If the CMake cache doesn't already exist, configure it for the first time.
# If it does already exist, `cmake --build` will reconfigure if needed.
$(CMAKECACHE):
	@cmake --preset $(preset) -B $(BUILD_DIR)
