#include "trivia.h"
#include "player.h"
#include "guy.h"

#define NUM_TRIVIA 212

trivia_t trivia[NUM_TRIVIA]={
	{0,2,	// mushy hollow
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The original publisher didn't",
	 "approve of these guys being",
	 "called Shrooms, so  now they",
	 "are Mushies!"}},
	{0,2,	// mushy hollow
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The Dragon's Flame spell is",
	 "one of the two spells directly",
	 "ripped from Dr. Lunatic weapons.",
	 "Bet you'll never guess the other!"}},
	{0,3,	// grassy knoll
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*4,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level was named after",
	 "the place where JFK was shot",
	 "from, supposedly.",
	 ""}},
	{0,3,	// grassy knoll
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*12,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Sometimes it's hard to come",
	 "up with level names.",
	 "",
	 ""}},
	{0,3,	// grassy knoll
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*20,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Egg Sacs had to be modified to",
	 "drop less coins.  They used to",
	 "drop eight times as many as they",
	 "do now!"}},
	{0,3,	// grassy knoll
	{TC_KILL,TC_NOTVAR,TC_NONE,TC_NONE},
	{MONS_EGGSAC,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Please, try to sometimes use",
	 "spells other than Seeker Bolt!",
	 "It's good to have variety.",
	 ""}},
	{0,4,	// just a puddle
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"",
	 "Whoa, don't fall in!",
	 "",
	 ""}},
	{0,4,	// just a puddle
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*24,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The Challenge Mode is loosely",
	 "based on the Tony Hawk games.",
	 "I am an absolute Tony Hawk NUT.",
	 "They are just PERFECT games!!"}},
	{0,4,	// just a puddle
	{TC_KILL,TC_NOTVAR,TC_NONE,TC_NONE},
	{MONS_SHROOM,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"To use Ice Blast effectively, you",
	 "must fire from point-blank range.",
	 "It's a very weak spell.  But Ice",
	 "Beam is great once you get it!"}},
	{0,5,	// grasslands
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level has the most boring",
	 "name in Kid Mystic history.",
	 "",
	 ""}},
	{0,5,	// grasslands
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*13,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"",
	 "But it's descriptive!",
	 "",
	 ""}},
	{0,5,	// grasslands
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{3+256*3,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"This is the only piece of the",
	 "Armageddon Sword which is in",
	 "a regular level.  The others",
	 "are all in hidden levels."}},
	{0,5,	// grasslands
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"If you didn't know, you can",
	 "step on Eensy Weensies in Kid",
	 "Mystic!  It's very satisfying.",
	 ""}},
	{0,14,	// the bridge
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_SUBTIME,TE_VAR},
	{30*2,0},
	{"Originally, the boss here",
	 "was just a Mama Spider,",
	 "but it was changed to make",
	 "the game more unique!"}},
	{0,14,	// the bridge
	{TC_KILL,TC_TIMED2,TC_VAR,TC_NOTVAR},
	{MONS_OCTOBOSS,0,0,1},
	{TE_VAR,TE_SUBTIME},
	{1,30*12},
	{"",
	 "Where'd this bridge come from?",
	 "",
	 ""}},
	{0,14,	// the bridge
	{TC_TIMED2,TC_NONE,TC_VAR,TC_NOTVAR},
	{0,0,1,2},
	{TE_VAR,TE_NONE},
	{2,0},
	{"Isn't it a shame that half the",
	 "powerups are on this side of",
	 "the bridge?  That's a holdover",
	 "from the Mama Spider's reign."}},
	{0,15,	// the docks
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*10,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is a really simple level.",
	 "It was the first one added",
	 "for the updated version of",
	 "Kid Mystic!"}},
	{0,15,	// the docks
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{3+7*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Runny is a popular Fairy.  I",
	 "bet you used him a lot getting",
	 "past those nasty M-Y-S-T-I-C",
	 "challenges!"}},
	{0,16,	// plants gone wild
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*10,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is a work of fiction.  Any",
	 "resemblance to actual persons,",
	 "living or dead, is entirely",
	 "coincidental."}},
	{0,16,	// plants gone wild
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{1+62*256,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{0,30*5},
	{"Casty Fairy is more useful than",
	 "he seems.  He adds 10 levels to",
	 "your spells, which is great when",
	 "you are very weak."}},
	{0,16,	// plants gone wild
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"Just don't use Dragon's Flame or",
	 "Energy Barrage with him... he'll",
	 "suck your life away!  Stick to",
	 "bigger spells."}},
	{0,17,	// trick shot
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*10,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I came up with this level while",
	 "trying to think of a way to test",
	 "other types of player skills.",
	 "So it tests your bank shot skill!"}},
	{0,17,	// trick shot
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{14+14*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"People like to forget about",
	 "Blocky, because he seems kinda",
	 "boring.  But he has gotten me",
	 "through more than one jam!"}},
	 // chapter 2
	{1,2,	// creepy creek
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Look at you... hunting down",
	 "every last little Spitter, for",
	 "what?  35 coins.  That's just",
	 "desperate."}},
	{1,2,	// creepy creek
	{TC_KILL,TC_NOTVAR,TC_NONE,TC_NONE},
	{MONS_EGGSAC,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Inferno was actually based",
	 "on a much cooler spell from",
	 "the gamelet Boboli The Mighty",
	 "Knight."}},
	{1,2,	// creepy creek
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{40+51*256,1,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*6},
	{"This M-Y-S-T-I-C was the",
	 "absolute bane of half of the",
	 "beta testers.  It's been made",
	 "much easier for you!"}},
	{1,2,	// creepy creek
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,2,1,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"",
	 "It's still horrible, isn't",
	 "it?",
	 ""}},
	{1,3,	// mush aid
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_SUBTIME,TE_VAR},
	{30*8,1},
	{"This level has prompted tons of",
	 "questions from customers!  I",
	 "guess it's a tricky puzzle!",
	 ""}},
	{1,3,	// mush aid
	{TC_TIMED2,TC_VAR,TC_NOTVAR,TC_NONE},
	{0,1,2,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"The teleporting Mushlord maze is",
	 "really the heart of this level.",
	 "The rest was added to flesh out",
	 "the concept."}},
	{1,3,	// mush aid
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{59+32*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"The Healing spell!  Definitely",
	 "one of the most widely used",
	 "spells in the game.  Not the",
	 "most exciting spell, though."}},
	{1,3,	// mush aid
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{51+22*256,3,0,0},
	{TE_VAR,TE_NONE},
	{3,0},
	{"The hidden hedge shooting was",
	 "a pretty dumb concept.  It's",
	 "just not a clever puzzle... more",
	 "like an eye test!  Sorry."}},
	{1,5,	// abandoned village
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Some people really like this",
	 "level for having a sort of hint",
	 "of storyline to it.  Seems that",
	 "people like stories!"}},
	{1,5,	// abandoned village
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{23+26*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"The Berserk spell is a personal",
	 "favorite of mine!  Check out the",
	 "cool glowy effect it makes.  And",
	 "it's the key to many goals!"}},
	{1,5,	// abandoned village
	{TC_KILL,TC_NOTVAR,TC_NONE,TC_NONE},
	{MONS_SHROOM,1,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*7},
	{"I never like illogical events like",
	 "this. Why does this bridge appear",
	 "when the Mushies are gone?",
	 "Other games do it all the time..."}},
	{1,5,	// abandoned village
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,2,1,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"But it just upsets my sense of",
	 "\"reality\".  Of course, I still",
	 "did it.  But usually, I do try to",
	 "have a 'logical' reason for things."}},
	{1,6,	// spider's lair
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level is a popular one. It's",
	 "very simple, but it's just a fun",
	 "arena to battle it out, and rake",
	 "in coins at the same time!"}},
	{1,6,	// spider's lair
	{TC_KILL,TC_NOTVAR,TC_NONE,TC_NONE},
	{MONS_EGGSAC,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{0,30*8},
	{"Summon Ptero is an adorable spell",
	 "that I really like.  They're kind",
	 "of worthless, but I always love",
	 "summoning minions in games."}},
	{1,6,	// spider's lair
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"I guess I like games where I",
	 "don't have to do the playing for",
	 "myself!  Yet ironically, I don't",
	 "like games full of cinematics!"}},
 	{1,6,	// spider's lair
	{TC_KILL,TC_NOTVAR,TC_NONE,TC_NONE},
	{MONS_MAMASPDR,2,0,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"One of these Mama Spiders was",
	 "originally the boss of Chapter 1.",
	 "The Optimum Octon is much more",
	 "frightening, huh?"}},
	{1,11,	// among the hedges
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This always seems like an odd",
	 "level to me.  It's just sort of",
	 "a weird combination of areas.",
	 "Kinda short too."}},
	{1,11,	// among the hedges
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{58+42*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Whenever I wonder what to put",
	 "next in a level, the first thing",
	 "that always comes to mind is",
	 "AMBUSH!!!  And here it comes."}},
	{1,11,	// among the hedges
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{16+27*256,1,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*8},
	{"Many people don't know how the",
	 "Stoneskin spell works.  What it",
	 "does is to divide the damage",
	 "you take in half."}},
	{1,11,	// among the hedges
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,2,1,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"This actually makes you immune",
	 "to anything that does 1 damage",
	 "(after your armor subtracts),",
	 "which is a lot of stuff!"}},
	{1,13,	// hidden temple
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*3,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"When coming up with new levels",
	 "to add to Kid Mystic, I thought",
	 "of ancient temples hidden in",
	 "jungles. This was my take."}},
	{1,13,	// hidden temple
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The 'welcome mat' puzzle says",
	 "WELCOME on it in very stylized",
	 "letters, if you couldn't tell.",
	 "It's meant to look Incan."}},
	{1,13,	// hidden temple
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*30,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Some people are convinced these",
	 "enemies are bears.  They're not.",
	 "They're ancient Incan robots!",
	 "Cooked in kilns, no less."}},
	{1,13,	// hidden temple
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{77+105*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Vampy is a fairly special-use",
	 "Fairy.  In a level where you will",
	 "have rapid-fire and a lot to",
	 "shoot at, she's great!"}},
	{1,14,	// lost in the woods
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is the first of 2 levels",
	 "which have randomly generated",
	 "layouts.  They are my favorites!",
	 "Always an adventure."}},
	{1,14,	// lost in the woods
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*20,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I like the M-Y-S-T-I-C letters",
	 "in this level, because they are",
	 "a different challenge than usual -",
	 "they require memorization!"}},
	{1,14,	// lost in the woods
	{TC_KILL,TC_KILL,TC_NOTVAR,TC_NONE},
	{MONS_OCTOPUS,MONS_SERPENT,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Smashy is one of my favorite",
	 "Fairies.  If you want to just",
	 "use fireballs, he's perfect!",
	 "Recognize his hammer?"}},
	{1,15,	// river rafting
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*2,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"When updating Kid Mystic, I",
	 "wanted to add whole new types",
	 "of play.  So I decided on river",
	 "rafting!"}},
	{1,15,	// river rafting
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*11,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The side path for the Fairy Bell",
	 "was intended to be hidden, but",
	 "I couldn't make it any smaller",
	 "without making it unusable!"}},
	{1,15,	// river rafting
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*19,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level had to toned down",
	 "a lot.  It's hard to dodge those",
	 "rocks!",
	 ""}},
	{1,15,	// river rafting
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{28+67*256,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{0,30*7},
	{"Cheapy really changes the game",
	 "when you use him!  With his help,",
	 "you can cast Armageddon twice,",
	 "or fire dozens of Seeker Swarms!"}},
	{1,15,	// river rafting
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"Of course, you get no fireballs!",
	 "So it really changes how you",
	 "play.",
	 ""}},
	{1,16,	// temple of kings
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*6,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The Golden Blockheads have been",
	 "slowed down, and their lasers",
	 "weakened greatly from how they",
	 "started."}},
	{1,16,	// temple of kings
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*13,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I liked them how they originally",
	 "were!  A fun, not too tough,",
	 "challenge.  But some testers just",
	 "couldn't pass them at all!"}},
	{1,16,	// temple of kings
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{56+2*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Nobody likes using Toughy. Moving",
	 "that slow is just not fun!  But",
	 "I wanted some Fairies to have big",
	 "bonuses with big penalties."}},
	{1,16,	// temple of kings
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{40+49*256,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"I don't like Blocko's name.  But",
	 "his simple, patterned behavior is",
	 "fun, like a classic arcade shooter",
	 "boss!"}},
	{1,16,	// temple of kings
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{42+34*256,2,0,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"",
	 "Now that's a whole lot of orbs.",
	 "",
	 ""}},
	{1,4,	// hidden clearing
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*3,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is not much of a level.  It",
	 "was meant just as a hidden spot",
	 "to get the sword piece, but since",
	 "Challenge Mode needed all pieces..."}},
	{1,4,	// hidden clearing
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*10,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I had to beef it up to add some",
	 "fun! It's still super easy, but",
	 "it has some pretty tricky goals",
	 "to do."}},
	{1,4,	// hidden clearing
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*30,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"",
	 "Firefly was the best TV show of",
	 "all time, as of this writing.",
	 ""}},
	{1,12,	// spooky pass
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Originally, the boss here was",
	 "just Mush, from Dr. Lunatic. I",
	 "like these goats much better!",
	 ""}},
	{1,12,	// spooky pass
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level has a very silly",
	 "layout.  I don't know why",
	 "there are teleporters in this",
	 "mountain pass."}},
	{1,12,	// spooky pass
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"If you didn't get the joke,",
	 "these goats are intended to",
	 "be the 3 Billy Goats Gruff.",
	 ""}},
	{1,12,	// spooky pass
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*32,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Disgruntled Gruff was",
	 "originally named Gruffy Gruff.",
	 "That seemed a little too",
	 "redundant, though."}},
	{1,12,	// spooky pass
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*42,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Though it wasn't intentional,",
	 "the 3 goats almost exactly mirror",
	 "the 3 Ancients in one of my",
	 "favorite games, Diablo II."}},
	{1,12,	// spooky pass
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*49,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"On a more intentional note,",
	 "Madcap Mode is a rip-off of the",
	 "Nightmare Mode in Diablo II. But",
	 "to be fair, it's a common idea!"}},
	{2,6,	// The gatehouse
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I liked the idea of having to",
	 "get the front gate of the castle",
	 "open... I mean, Bobby wouldn't",
	 "just let you walk in!"}},
	{2,6,	// The gatehouse
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{52+34*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"I think Ice Beam is underused.",
	 "It's actually quite effective,",
	 "and it looks cool!  No pun",
	 "intended."}},
	{2,6,	// The gatehouse
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{24+32*256,1,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*9},
	{"I can't tell you how many times",
	 "people had trouble with this",
	 "puzzle!  Some of it was my fault",
	 "though..."}},
	{2,6,	// The gatehouse
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,2,1,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"Because the walls don't change",
	 "their top when they descend,",
	 "some people couldn't visualize",
	 "them as walls opening up!"}},
	{2,9,	// The library
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*4,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I apologize for the long",
	 "pointless jog at the beginning",
	 "of this level.  I don't know why",
	 "I did it, or why I left it in!"}},
	{2,9,	// The library
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*14,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"When making this chapter, each",
	 "original level was meant to be",
	 "a real room of a castle.  Hence",
	 "the library, ballroom, etc."}},
	{2,9,	// The library
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*21,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Original levels are all the ones",
	 "which have Spellbooks.  The new",
	 "levels are the ones with Fairies.",
	 "Ones with neither are old too."}},
	{2,9,	// The library
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{84+20*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"",
	 "Best stupid joke in the game!",
	 "",
	 "(Librarian humor!)"}},
	{2,9,	// The library
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{40+25*256,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"The Life spell is just as boring",
	 "as the Healing spell, but more",
	 "powerful.  But like Healing, it's",
	 "a vital part of your arsenal!"}},
	{2,9,	// The library
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{53+64*256,2,0,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"The joke here is that there are",
	 "an awful lot of crappy romance",
	 "novels.  I wish I had made them",
	 "all pink like real life, though."}},
	{2,9,	// The library
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{60+38*256,3,0,0},
	{TE_VAR,TE_NONE},
	{3,0},
	{"There's a hidden joke in here...",
	 "check the bookshelves!",
	 "",
	 "It's a Twilight Zone reference."}},
	{2,11,	// The ballroom
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It's always good to have a level",
	 "which is nothing but absolute",
	 "mayhem. In fact, that's the name",
	 "of such a level in Dr. Lunatic!"}},
	{2,11,	// The ballroom
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{71+22*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Energy Storm... eh... well, it",
	 "beats Energy Barrage.",
	 "",
	 ""}},
	{2,11,	// The ballroom
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*20,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Eye Guys are stolen from Eddie",
	 "Galaxy, though in that game they",
	 "breathe fire rather than spitting",
	 "nifty sonic waves."}},
	{2,13,	// guest chambers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*10,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level is loooong and complex.",
	 "No real tricky puzzles, no big",
	 "battles, just a whole lotta level.",
	 "Is that good or bad?  You pick!"}},
	{2,13,	// guest chambers
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{23+75*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"This M-Y-S-T-I-C is, along with",
	 "Creepy Creek, the hardest in the",
	 "game.  It too has been toned",
	 "down a bit from where it started!"}},
	{2,13,	// guest chambers
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{84+91*256,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"Hyper Inferno!  Takes the goofy",
	 "Inferno spell and makes it down-",
	 "right cool!  It's very costly to",
	 "cast, but looks great."}},
	{2,13,	// guest chambers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*30,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Spooky Castle was originally",
	 "called Castle Heinous.  I really",
	 "liked that name!  But the publisher",
	 "felt it could be mispronounced."}},
	{2,13,	// guest chambers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*40,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Heinous or spooky, why does this",
	 "evil place have guest chambers",
	 "at all?",
	 "With hopscotch even!"}},
	{2,13,	// guest chambers
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{56+49*256,2,0,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"These are supposed to be the",
	 "type of toilets they have in",
	 "castles - a seemingly bottomless",
	 "hole in the floor.  Drafty!"}},
	{2,16,	// the vault
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is a very, very simple level.",
	 "It's just the extra stuff that's",
	 "tricky! This puzzle is the #1",
	 "question I get on this game!"}},
	{2,16,	// the vault
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"There are two clues to help you:",
	 "",
	 "1. The vault is Roman.",
	 "2. The combination is 16!"}},
	{2,16,	// the vault
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{18+35*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Not that you care, but the 'I' in",
	 "this combination may be done",
	 "with or without serifs. Which way",
	 "do you do it?"}},
	{2,16,	// the vault
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{32+8*256,1,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*9},
	{"Tough choice here - 500 coins,",
	 "which you could earn in a couple",
	 "battles, or a new spell, which is",
	 "one of a kind!"}},
	{2,16,	// the vault
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,2,1,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"The spell in question is Insane",
	 "Rage. Odd name, but cool spell!",
	 "It was hard to come up with a",
	 "name that meant More Berserk."}},
	{2,18,	// violent eyes
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"These enemies are an homage to",
	 "Metal Gear Solid, forcing you",
	 "to sneak around.  At high levels",
	 "they're pretty harmless though."}},
	{2,18,	// violent eyes
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*12,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"They're also based on a very",
	 "similar enemy in Baldur's Gate:",
	 "Dark Alliance - spinning eyes that",
	 "zap you to death if they see you."}},
	{2,18,	// violent eyes
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*20,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"And in case you didn't know, this",
	 "level name is a play on \"When",
	 "Irish Eyes Are Smiling\", a very",
	 "famous old song."}},
	{2,18,	// violent eyes
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*27,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Which I mistakenly thought was",
	 "called \"Irish Eyes A-Smiling\".",
	 "",
	 "Oops!"}},
	{2,18,	// violent eyes
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{60+4*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Smarty is the Fairy in this level.",
	 "If you look closely at him, you",
	 "can see that he has incredibly",
	 "thick glasses.  Exciting!"}},
	{2,17,	// twisty passages
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is my favorite level!  Not",
	 "only is it random, but it even",
	 "randomly locks off parts and adds",
	 "keys to find.  Fun every time."}},
	{2,17,	// twisty passages
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*20,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The level name is a geek joke.",
	 "It is a reference to Zork, or",
	 "Colossal Cave, or Adventure.",
	 "Text adventure games."}},
	{2,17,	// twisty passages
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*40,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The Trapazoids get me every",
	 "time.  They really are sneaky!",
	 "That wasn't actually intended,",
	 "they just came out that color."}},
	{2,17,	// twisty passages
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*60,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Richey Fairy is pretty useful.",
	 "He originally made enemies drop",
	 "more coins, but now he raises",
	 "the odds of big coins dropping."}},
	{2,21,	// guardian battle
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level is not in the normal",
	 "game, of course, but is sort of",
	 "a combination of the four Tower",
	 "Guardians, which are."}},
	{2,21,	// guardian battle
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Aren't these cool looking",
	 "enemies? They'd be great rooks",
	 "in a chess set.",
	 ""}},
	{2,21,	// guardian battle
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*30,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Hey, try to earn a 4 combo!",
	 "It's not required, and there's",
	 "no reward for it, but WHAT a",
	 "challenge!"}},
	{2,21,	// guardian battle
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*37,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Well, it's easy with",
	 "Armageddon, of course.  But",
	 "try without using that.",
	 "Mr. Smarty Pants."}},
	{2,19,	// whack-a-zoid
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Another favorite of mine.",
	 "I really wanted to provide a",
	 "variety of gameplay in this",
	 "update, so here's some!"}},
	{2,19,	// whack-a-zoid
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*18,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Healey Fairy is not too popular.",
	 "Maybe he heals too slowly.  His",
	 "wings have red crosses on them,",
	 "though it is hard to tell."}},
	{2,19,	// whack-a-zoid
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*30,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I hate to give away the big",
	 "secret, but this level gets",
	 "VERY easy with Energy Storm",
	 "and Cheapy Fairy!"}},
	{2,20,	// castle sewers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It took no less than 3 days of",
	 "continuous head-scratching to",
	 "finally come up with an idea for",
	 "this last Chapter 3 level."}},
	{2,20,	// castle sewers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*12,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Then it took another day of",
	 "self-kicking to work out the",
	 "puzzle of the drainage canals.",
	 ""}},
	{2,20,	// castle sewers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*19,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I couldn't seem to work out a",
	 "way for it to actually be a",
	 "puzzle!  In the end, it's almost",
	 "trivial. Kinda looks cool, tho."}},
	{2,20,	// castle sewers
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{125+26*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"The fairy in this level is",
	 "Savey, one of the most unique.",
	 "He also looks kinda cute. Very",
	 "handy when walking near water!"}},
	{2,20,	// castle sewers
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{70+50*256,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"You may not even notice, but",
	 "when you walk across a canal,",
	 "you are sliding on the muck at",
	 "the bottom.  Yuck."}},
	{2,7,	// off the deep end
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is the least hidden hidden",
	 "level ever.  It's pretty much just",
	 "hanging out, hoping you don't",
	 "decide to look behind the castle."}},
	{2,7,	// off the deep end
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*20,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Isn't it odd that Kid Mystic",
	 "will blindly hop into a lake, but",
	 "has the brains not to fall off a",
	 "cliff?  Double standard!"}},
	{2,7,	// off the deep end
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*27,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Isn't it odder still that coins",
	 "magically float right across the",
	 "void?  Well, it wouldn't be much",
	 "fun if they all just fell!"}},
	{2,7,	// off the deep end
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*40,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level is really far too",
	 "easy.  It was originally meant",
	 "to be abnormally tough, to make",
	 "you really earn that sword."}},
	{2,7,	// off the deep end
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*47,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"",
	 "Don't ask me what happened.",
	 "I just work here.",
	 ""}},
	{2,15,	// the keep
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*7,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"In a castle, the keep is the",
	 "central tower, the most defended",
	 "part.  That's your medieval",
	 "architecture lesson for today."}},
	{2,15,	// the keep
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"A Lookey-Loo is someone who is",
	 "looking in unnecessarily, like a",
	 "rubbernecker or nosey guy. That's",
	 "your slang lesson for today."}},
	{2,15,	// the keep
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This boss is actually based a bit",
	 "on a scene from Stephen King's",
	 "novel \"It\", which is my favorite",
	 "book of all time!"}},
	{2,15,	// the keep
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*35,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Other recommended reading?",
	 "Ender's Game - Orson Scott Card",
	 "The Dark Tower series - King",
	 "Everything else - King!"}},
	{2,15,	// the keep
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*45,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Vampy is very effective against",
	 "enemies like this that can block",
	 "your shots.  She'll still heal",
	 "you for blocked hits!"}},
	{2,15,	// the keep
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*55,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Speaking of stealing from my",
	 "other games, the Lookey-Loo's",
	 "sounds are the sounds of the",
	 "final boss from Eddie Galaxy."}},
	 // chapter 4
	{3,6,	// toasty caverns
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It goes without saying that",
	 "there had to be a level where",
	 "you precariously balance over",
	 "hot lava in the cavern chapter!"}},
	{3,6,	// toasty caverns
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{3+38*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Liquify was the obvious choice",
	 "to put in this level.  You need",
	 "to overcome your fear of lava to",
	 "reach it too."}},
	{3,7,	// the mines
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I think this works well as a",
	 "themed level.  You really feel",
	 "like you're heading down to lower",
	 "levels of a mine... a coin mine?"}},
	{3,7,	// the mines
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{86+11*256,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{0,30*8},
	{"Like its little brother, Seeker",
	 "Swarm is the most useful spell in",
	 "the game, only 3 times better!",
	 ""}},
	{3,7,	// the mines
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"Seeker Swarm and Liquify are",
	 "very ineffective in tight quarters.",
	 "That's when Energy Storm actually",
	 "becomes useful!"}},
	{3,15,	// gastro-pods
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*10,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Sniper Snails were originally",
	 "named Sneaky Snails.  But frankly,",
	 "they're not that sneaky!",
	 ""}},
	{3,15,	// gastro-pods
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*20,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Gastropod is the class of animal",
	 "that snails and slugs are, if you",
	 "didn't know.  And these things",
	 "you are opening are pods. Get it?!"}},
	{3,15,	// gastro-pods
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*28,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Gastropod means stomach-foot.",
	 "It's because they crawl around",
	 "on their stomachs.  Latin",
	 "lesson for today!"}},
	{3,15,	// gastro-pods
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{124+106*256,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{0,30*8},
	{"Mighty is supposed to be the",
	 "ultimate Fairy, boosting all",
	 "your abilities, but draining",
	 "your life and magic."}},
	{3,15,	// gastro-pods
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"To be precise, he gives you 25%",
	 "more speed, 25% damage boost,",
	 "25% more defense, and 10% less",
	 "mana cost for spells."}},
	{3,9,	// obnoxious
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{28+31*256,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{0,30*8},
	{"In a survey of beta testers,",
	 "Summon Golem got the most",
	 "votes for favorite spell!",
	 ""}},
	{3,9,	// obnoxious
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,1,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*8},
	{"The 3D model of the golem is",
	 "made entirely of cubes.",
	 "Not just because I'm lazy, it",
	 "was an artistic choice."}},
	{3,9,	// obnoxious
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,2,1,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"The testers found that the golem",
	 "was great for blocking shots",
	 "in Madcap mode, where each hit",
	 "is quite unhealthy."}},
	{3,9,	// obnoxious
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level began unnamed, but in",
	 "testing it out, running through",
	 "those tiny, twisty passages, the",
	 "right name just came to me!"}},
	{3,9,	// obnoxious
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{37+51*256,3,0,0},
	{TE_VAR,TE_NONE},
	{3,0},
	{"I told you, I like to put in",
	 "ambushes!  Actually, I like",
	 "playing them, too.  Kind of tense",
	 "getting prepared for it and all."}},
	{3,10,	// bats
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{53+1*256,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"Steelskin is an awful lot like",
	 "Stoneskin.  It is far more",
	 "powerful, though - You take 1/8",
	 "damage, making most hits harmless!"}},
	{3,10,	// bats
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level was named before it",
	 "was made... but calling it",
	 "Caves Of Obnoxiousness II wouldn't",
	 "have been too wrong!"}},
	{3,10,	// bats
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Though you may recognize the",
	 "Scarier Bats and Die Uberbat",
	 "from Supreme With Cheese, they",
	 "were in Kid Mystic first."}},
	{3,10,	// bats
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{53+15*256,2,0,0},
	{TE_VAR,TE_SUBTIME},
	{2,30*8},
	{"Die Uberbat is a pretty pathetic",
	 "boss. It takes many hits to beat",
	 "him, but he's pretty harmless.",
	 ""}},
	{3,10,	// bats
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,3,2,0},
	{TE_VAR,TE_NONE},
	{3,0},
	{"Like the Lookey-Loo, he is very",
	 "loosely based on a Stephen King",
	 "story! The story Graveyard Shift",
	 "from Skeleton Crew, to be exact."}},
	{3,12,	// red river rafting
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I had to add the on-foot bits",
	 "of this level just because the",
	 "maximum level height allowed",
	 "doesn't make for a long ride!"}},
	{3,12,	// red river rafting
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*12,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"On the plus side, it results in",
	 "a more involved level, with much",
	 "more substance.  And slugs!",
	 ""}},
	{3,12,	// red river rafting
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{28+2*256,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{0,30*7},
	{"Since you're on lava, the log in",
	 "this level is made of petrified",
	 "wood. VERY petrified.",
	 "Otherwise it would burn up!"}},
	{3,12,	// red river rafting
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{0,2,0,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"Don't try this at home, though.",
	 "In real life, just getting NEAR",
	 "lava is deadly.  It's HOT!",
	 "And it gives off deadly fumes."}},
	{3,12,	// red river rafting
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{48+122*256,1,0,0},
	{TE_VAR,TE_NONE},
	{1,0},
	{"Shooty isn't that useful... but",
	 "he has no drawbacks!  He wears a",
	 "Rambo headband and holds a big",
	 "gun."}},
	{3,13,	// smashball
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"In case you can't tell, this",
	 "level is a take-off on Breakout,",
	 "or Arkanoid for you younguns.",
	 ""}},
	{3,13,	// smashball
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Some testers found this to be",
	 "super hard, but I thought it was",
	 "easy from the beginning!  I did",
	 "make it much easier, though."}},
	{3,13,	// smashball
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*22,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It's strange sometimes how what",
	 "you think might be too simple is",
	 "actually near-impossible to some",
	 "one else.  Testing is the key!"}},
	{3,13,	// smashball
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{25+49*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Haggly is one of the Fairies who",
	 "has no drawback.  It'd be tough",
	 "to give him one, since you can",
	 "just turn him on for shop visits!"}},
	{3,14,	// puzzling caverns
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*8,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This was the last level made. It",
	 "is supposed to be the 'ultimate'",
	 "challenge level.",
	 ""}},
	{3,14,	// puzzling caverns
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{74+93*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"The lights-out puzzle is totally",
	 "killer.  Every tester had tons",
	 "of problems with it, and it was",
	 "simplified, but still is hard."}},
	{3,14,	// puzzling caverns
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{52+103*256,1,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*8},
	{"This is the easiest box-pushing",
	 "'puzzle' in the world.  I just",
	 "threw it together, because I find",
	 "these puzzles way too annoying!"}},
	{3,14,	// puzzling caverns
	{TC_TIMED2,TC_NOTVAR,TC_VAR,TC_NONE},
	{52+103*256,2,1,0},
	{TE_VAR,TE_NONE},
	{2,0},
	{"The only reason it's even here",
	 "is that I needed 4 different",
	 "puzzle rooms.",
	 ""}},
	{3,14,	// puzzling caverns
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{74+103*256,3,0,0},
	{TE_VAR,TE_NONE},
	{3,0},
	{"These are hard to get through,",
	 "but the simple trick is to just",
	 "cast Steelskin, and waltz right",
	 "through the beams!"}},
	{3,14,	// puzzling caverns
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{52+93*256,4,0,0},
	{TE_VAR,TE_NONE},
	{4,0},
	{"This Peeping Bomb 'puzzle' is a",
	 "joke, because you can just blow",
	 "them all up with spells!  Oh",
	 "well.  Can't all be gems."}},
	{3,14,	// puzzling caverns
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{63+69*256,5,0,0},
	{TE_VAR,TE_NONE},
	{5,0},
	{"Scary isn't as useful as I had",
	 "hoped, but I also didn't want",
	 "100% defense against attacks.",
	 "Chicken Feathers are better!"}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*8,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Richie Lich appears in as many",
	 "Hamumu games as Bouapha does!",
	 "",
	 "That's a lot!"}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*16,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"He's the 'Ancient Evil' in Spooky",
	 "Castle (starring alongside Bouapha",
	 "of course).",
	 ""}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*24,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"He is in The Crypt in Dr. Lunatic,",
	 "though of course, he reappears",
	 "in countless add-ons as well.",
	 "(Again, with Bouapha)"}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*32,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"And here he is, guarding the",
	 "sword piece in Kid Mystic. This",
	 "is his only appearance without",
	 "his usual nemesis, Bouapha."}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*40,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Bouapha actually is in more",
	 "games if you count the original",
	 "SPISPOPD, but that is technically",
	 "by Jamul Software, so there!"}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*48,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Richie's name is a play on",
	 "Richie Rich, and of course the",
	 "word Lich, which is a type of",
	 "evil spirit, or just a corpse."}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*56,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Armageddon is a term for the",
	 "end of the world. It's meant to",
	 "imply that this sword is quite",
	 "powerful."}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*62,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Along with the name, the skulls",
	 "on the sword also imply that it",
	 "is evil. Maybe it is!",
	 ""}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*70,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"A discussion point: Is it okay",
	 "to use evil to defeat evil? Or",
	 "could it be that in using evil,",
	 "you become evil?"}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*78,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I guess it's a matter of if",
	 "the ends justify the means. I'm",
	 "inclined to think that you must",
	 "always be good, for any cause."}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*86,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Can one really be said to have",
	 "defeated Evil itself, if one is",
	 "evil in method?  See how deep",
	 "Hamumu games run?"}},
	{3,8,	// arma shrine
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*60+30*55,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"If you're reading this, your",
	 "time is almost up!",
	 "",
	 ""}},
	{3,11,	// bobby khan
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Here it is, the grand finale!",
	 "This is probably the toughest",
	 "boss in a Hamumu game.",
	 "I'm pretty proud of it!"}},
	{3,11,	// bobby khan
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Bobby Khan is a play on Genghis",
	 "Khan.  Khan means king, so",
	 "Genghis is just a name... and",
	 "so is Bobby!"}},
	{3,11,	// bobby khan
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*22,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Making him turn out to be an",
	 "old man (obviously an homage to",
	 "Scooby Doo) was just made up",
	 "when I made the ending movie."}},
	{3,11,	// bobby khan
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*30,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Originally, the game was titled",
	 "\"Kid Mystic: The Wrath Of Bobby",
	 "Khan\", but the publisher said",
	 "it was too similar to Star Trek."}},
	{3,11,	// bobby khan
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*37,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"",
	 "Doesn't anyone understand",
	 "parody anymore?",
	 ""}},
	 // bonus
	{0,18,	// stick stream
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Everybody loves Happy Stick!",
	 "These are the lamest stick",
	 "monsters of all.  I figured being",
	 "lame is part of the charm."}},
	{0,18,	// stick stream
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I don't feel right making a",
	 "game with no Happy Stick in it,",
	 "so I had to make these levels.",
	 ""}},
	{0,19,	// ker-splat
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*10,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I wanted to add some seriously",
	 "tough bonus levels that hit",
	 "elements of the game you don't",
	 "see elsewhere."}},
	{0,19,	// ker-splat
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"",
	 "Of course, this one isn't tough",
	 "at all.  But hey, it's unique!",
	 ""}},
	{0,19,	// ker-splat
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It was meant to be beaten by",
	 "stepping on the Eensies, but",
	 "you can finish a lot quicker with",
	 "the help of the Pointy Hat!"}},
	{1,18,	// forging a head
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"There's one Happy Stick bonus",
	 "level for each chapter, and one",
	 "special bonus level.  I knew I",
	 "had to make a 999 combo goal."}},
	{1,18,	// forging a head
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"",
	 "Somebody would've tried for it",
	 "anyway, might as well reward it.",
	 ""}},
	{1,18,	// forging a head
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"In case you can't tell, the Kilns",
	 "in this level are abnormally",
	 "active.",
	 ""}},
	{1,18,	// forging a head
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*35,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The 3D model for the Kiln has",
	 "a set of gears underneath it,",
	 "barely visible when the hatch",
	 "opens."}},
	{1,18,	// forging a head
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*42,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It's always disappointing that",
	 "I make these detailed models,",
	 "but can't show their full detail",
	 "or nifty animations."}},
	{1,18,	// forging a head
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*50,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"On the plus side, it means I",
	 "can get away with some very",
	 "bad modeling as well!",
	 ""}},
	{1,18,	// forging a head
	{TC_KILL,TC_NOTVAR,TC_NONE,TC_NONE},
	{MONS_INCAGEN,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"Blocko sure has a thing about",
	 "his orb collection, doesn't he?",
	 "",
	 ""}},
	{1,17,	// sticky webs
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I like these stick monsters.",
	 "Only the Happy Stick Corpses are",
	 "cooler.  Why are the first two",
	 "stick levels so short?"}},
	{1,17,	// sticky webs
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Because originally I meant for",
	 "them to be in with the chapter",
	 "they belong to, so I had to make",
	 "them start out kind of easy!"}},
	{1,17,	// sticky webs
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Why didn't I change them later?",
	 "Because if I made every improve-",
	 "ment I wanted, I would NEVER",
	 "release any games!"}},
	{1,17,	// sticky webs
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*35,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It sounds callous and artless,",
	 "but there comes a point where",
	 "you just have to say it's good",
	 "enough, and ship it."}},
	{1,17,	// sticky webs
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*45,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"If you played enough of this",
	 "game to be reading this, then",
	 "you probably agree that this",
	 "really is good enough!"}},
	{2,23,	// jeepers peepers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I wanted a level where you",
	 "really needed to hide from the",
	 "Peeping Bombs, so here it is!",
	 "The set of goals demands it."}},
	{2,23,	// jeepers peepers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This level is almost trivial -",
	 "I got all 5 goals on my second",
	 "try!  But I suppose it depends",
	 "on whether you know the layout."}},
	{2,23,	// jeepers peepers
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*24,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"It could've gone either way.",
	 "I just sort of threw it all in,",
	 "and gave it a try to see if it",
	 "worked. Only needed one change!"}},
	{2,22,	// stick graveyard
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"These guys are just lethal. I",
	 "had no qualms about making the",
	 "Happy Stick monsters vicious.",
	 "They must be respected!"}},
	{2,22,	// stick graveyard
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I describe Happy Stick Corpses",
	 "as Canadian.  If you understand",
	 "why, then you are a South Park",
	 "fan."}},
	{2,22,	// stick graveyard
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*25,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The Canadian look they have is",
	 "actually unintentional.  It's",
	 "just what happens when a stick",
	 "skeleton opens it's mouth!"}},
	{3,17,	// snailbait
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"The entire reason this level",
	 "exists is because I wanted to",
	 "make one level that requires the",
	 "use of Ice Beam."}},
	{3,17,	// snailbait
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Did you pass it without Ice",
	 "Beam?  If so, sorry.  It's MUCH",
	 "easier when you freeze them!",
	 ""}},
	{3,17,	// snailbait
	{TC_STEP,TC_NOTVAR,TC_NONE,TC_NONE},
	{20+19*256,0,0,0},
	{TE_VAR,TE_NONE},
	{0,0},
	{"I'm always leery of putting big",
	 "challenges far into a level,",
	 "because I hate repeating stuff.",
	 "This MYSTIC made me nervous."}},
	{3,16,	// subterranean sticks
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*5,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Because Happy Stick Bats are so",
	 "easy, I had to make their Happy",
	 "Stick level extra spicy.  So I",
	 "threw in the other Happy Sticks."}},
	{3,16,	// subterranean sticks
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*15,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"This is meant to be the big",
	 "crazy ultimate Happy Stick level,",
	 "but it's not THAT tough.  It's not",
	 "easy or anything, though."}},
	{3,16,	// subterranean sticks
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*30,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Well, this is the last level in",
	 "Challenge Mode.  If you played",
	 "them through in order reading the",
	 "trivia, then our journey is over!"}},
	{3,16,	// subterranean sticks
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*37,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"Thank you very much for buying",
	 "this game, and even more for",
	 "being so into it that you played",
	 "it to this point!"}},
	{3,16,	// subterranean sticks
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*44,0,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"I make these games to bring fun",
	 "to people, so I guess you got",
	 "that, or you wouldn't be this",
	 "far into the game."}},
	{3,16,	// subterranean sticks
	{TC_TIMED,TC_NONE,TC_NONE,TC_NONE},
	{30*51,0,0,0},
	{TE_VAR,TE_SUBTIME},
	{1,30*8},
	{"If you haven't played Madcap",
	 "Mode, give it a try!  It's very",
	 "intense. I even enjoy it myself!",
	 "Now I leave you with..."}},
	{3,16,	// subterranean sticks
	{TC_TIMED2,TC_VAR,TC_NONE,TC_NONE},
	{0,1,0,0},
	{TE_NONE,TE_NONE},
	{0,0},
	{"GOOD LUCK PASSING THE LEVEL",
	 "WITH THESE PLASTERED ALL",
	 "OVER THE SCREEN!!!!!!!!!!!",
	 "HAHAHAHAHAHA SUCKER!!!!!!!"}},
};

typedef struct visTrivia_t
{
	int x,y;
	char text[4][48];
	int timer;
	byte size;
	byte which;
} visTrivia_t;

byte trivVar[16];
visTrivia_t visTriv[8];
int trivTimer,subTimer;
sprite_set_t *trivSpr;

void InitTrivia(void)
{
	int i;

	trivSpr=new sprite_set_t("graphics\\trivia.jsp");
	for(i=0;i<16;i++)
		trivVar[i]=0;

	for(i=0;i<8;i++)
	{
		visTriv[i].timer=0;
		visTriv[i].size=0;
	}

	trivTimer=0;
	subTimer=0;
}

void ExitTrivia(void)
{
	delete trivSpr;
}

void TryToActivate(int t)
{
	int i;

	if((trivia[t].chapter!=player.worldNum || trivia[t].level!=player.levelNum) &&
		(trivia[t].chapter!=255))
		return;	// wrong chapter/level

	for(i=0;i<4;i++)
	{
		switch(trivia[t].condition[i])
		{
			case TC_TIMED:
				if(trivTimer!=trivia[t].condValue[i])
					return;
				break;
			case TC_KILL:
				if(MonsterExists(trivia[t].condValue[i]))
					return;
				break;
			case TC_VAR:
				if(!trivVar[trivia[t].condValue[i]])
					return;
				break;
			case TC_NOTVAR:
				if(trivVar[trivia[t].condValue[i]])
					return;
				break;
			case TC_TIMED2:
				if(subTimer)
					return;
				break;
			case TC_STEP:
				Guy *g;

				g=GetGoodguy();
				if(!g)
					return;

				if(g->mapx<(trivia[t].condValue[i]%256)-2 ||
				   g->mapx>(trivia[t].condValue[i]%256)+2 ||
				   g->mapy<(trivia[t].condValue[i]/256)-2 ||
				   g->mapy>(trivia[t].condValue[i]/256)+2)
				   return;
				break;
		}
	}
	// yes, activate it!
	for(i=0;i<8;i++)
	{
		if(visTriv[i].timer==0 && visTriv[i].size==0)
		{
			MakeNormalSound(SND_TRIVIA);
			visTriv[i].x=MGL_random(640-240)+120;
			visTriv[i].y=MGL_random(480-120)+60;
			if(t==NUM_TRIVIA-1)
				visTriv[i].timer=30*2;
			else
				visTriv[i].timer=30*7;
			visTriv[i].size=0;
			visTriv[i].which=t;
			break;
		}
	}
	for(i=0;i<2;i++)
	{
		switch(trivia[t].effect[i])
		{
			case TE_VAR:
				trivVar[trivia[t].effectVal[i]]=1;
				break;
			case TE_SUBTIME:
				subTimer=trivia[t].effectVal[i];
				break;
		}
	}
}

void UpdateTrivia(void)
{
	int i;

	trivTimer++;

	if(subTimer)
		subTimer--;

	for(i=0;i<NUM_TRIVIA;i++)
	{
		TryToActivate(i);
	}

	for(i=0;i<8;i++)
	{
		if(visTriv[i].timer)
		{
			visTriv[i].timer--;
			if(visTriv[i].size<30)
				visTriv[i].size+=3;
		}
		else if(visTriv[i].size)
			visTriv[i].size-=3;
	}
}

void RenderTrivia(MGLDraw *mgl)
{
	int i,j;
	byte n;

	for(i=0;i<8;i++)
	{
		if(visTriv[i].size)
		{
			//mgl->FillBox(visTriv[i].x-visTriv[i].size*4,visTriv[i].y-visTriv[i].size,visTriv[i].x+visTriv[i].size*4,visTriv[i].y+visTriv[i].size,0);
			//mgl->Box(visTriv[i].x-visTriv[i].size*4,visTriv[i].y-visTriv[i].size,visTriv[i].x+visTriv[i].size*4,visTriv[i].y+visTriv[i].size,31);
			n=(30-visTriv[i].size)/5;
			if(n==6)
				n=5;
			trivSpr->GetSprite(n)->Draw(visTriv[i].x,visTriv[i].y+5,mgl);
			if(visTriv[i].size==30)
			{
				for(j=0;j<4;j++)
					Print(visTriv[i].x-GetStrLength(trivia[visTriv[i].which].text[j],1)/2,visTriv[i].y-visTriv[i].size+4+j*15,trivia[visTriv[i].which].text[j],-31,1);
			}
		}
	}
}
