#!/bin/bash
set -euo pipefail

# Clean the installation directory just in case
if test -d build/dist; then
	rm -r build/dist
fi

# Require Steamworks SDK
if ! test -f external/steamworks_sdk/Readme.txt; then
	echo "ERROR: Steam release requires Steamworks SDK to be present"
	exit 1
fi

# Pre-extract Supreme8 installer to a Steam depot for maximum-speed access
# shellcheck disable=SC2016
7z x installers/supreme8_install.exe -o"build/dist/supreme8" \
	-x'!$PLUGINSDIR' -x'!*.exe' -x'!*.dll' -x'!profiles'

# Linux executables
echo "==== Linux build ===="
./container bash -c "
	set -euo pipefail
	cmake --preset linux-x86_64-release
	cmake --build build/cmake-linux-x86_64-release --target supreme
	cmake --install build/cmake-linux-x86_64-release --prefix build/dist/linux-exe --component generic/executables
	cmake --install build/cmake-linux-x86_64-release --prefix build/dist/linux-exe --component supreme/executables
	cmake --install build/cmake-linux-x86_64-release --prefix build/dist/assets --component supreme/assets
"

# Windows executables
echo "==== Windows build ===="
vagrant up windows
vagrant winrm windows --command 'C:/vagrant/tools/windows-vm/build-release-msvc.bat'
