#!/bin/bash
set -euo pipefail

# Clean the installation directory just in case
if test -d build/dist/mystic; then
	rm -r build/dist/mystic
fi

# Require Steamworks SDK
if ! test -f external/steamworks_sdk/Readme.txt; then
	echo "ERROR: Steam release requires Steamworks SDK to be present"
	exit 1
fi

# Pre-extract mystic_install.exe
7z x installers/mystic_install.exe -o"build/dist/mystic"
innoextract build/dist/mystic/setup.0 --output-dir "build/dist/mystic"  # implied app/
rm "build/dist/mystic/app/mystic.exe"

for platform in itch-linux itch-windows; do
	rsync --mkpath --archive build/dist/mystic/app/ build/dist/mystic/$platform/installers/mystic_install.exe/
done

# Linux executables
echo "==== Linux build ===="
./container bash -c "
	set -euo pipefail
	cmake --preset linux-x86_64-release
	# Steam
	cmake --build build/cmake-linux-x86_64-release --target mystic
	cmake --install build/cmake-linux-x86_64-release --strip --prefix build/dist/mystic/steam-linux --component generic/executables
	cmake --install build/cmake-linux-x86_64-release --strip --prefix build/dist/mystic/steam-linux --component mystic/executables
	cmake --install build/cmake-linux-x86_64-release --strip --prefix build/dist/mystic/steam-assets --component mystic/assets
	# Itch
	cmake --install build/cmake-linux-x86_64-release --strip --prefix build/dist/mystic/itch-linux --component generic/executables
	cmake --install build/cmake-linux-x86_64-release --strip --prefix build/dist/mystic/itch-linux --component mystic/executables
	cmake --install build/cmake-linux-x86_64-release --strip --prefix build/dist/mystic/itch-linux --component mystic/assets
"

# Windows executables
echo "==== Windows build ===="
tools/windows-cross/container bash -c "
	set -euo pipefail
	cmake --preset windows-i686-release -Wno-dev
	cmake --build build/cmake-windows-i686-release --target mystic
	# Steam
	cmake --install build/cmake-windows-i686-release --strip --prefix build/dist/mystic/steam-windows --component generic/executables
	cmake --install build/cmake-windows-i686-release --strip --prefix build/dist/mystic/steam-windows --component mystic/executables
	# Linux build already installs cross-platform Steam assets
	# Itch
	cmake --install build/cmake-windows-i686-release --strip --prefix build/dist/mystic/itch-windows --component generic/executables
	cmake --install build/cmake-windows-i686-release --strip --prefix build/dist/mystic/itch-windows --component mystic/executables
	cmake --install build/cmake-windows-i686-release --strip --prefix build/dist/mystic/itch-windows --component mystic/assets
"
