# Lunatic make.py
# Tad Hardesty, aka SpaceManiac, 2011
# Autogenerates build/generated.make
# usage: 'python tools/make.py target cxxflags lnflags'

from glob import glob
from sys import argv
from os import path
import re

target = argv[1]
cxxflags = argv[2]
linkflags = argv[3]

# don't compile certain files
blacklist = [
	'source/jamulsound.cpp',
	'source/music.cpp',
	'source/monsterlist.cpp',
	'source/monsterai1.cpp',
	'source/monsterai2.cpp',
	'source/monsterai3.cpp',
	'source/monsterai4.cpp',
	'source/textitems.cpp',
	'source/textrooms.cpp',
	'source/options.cpp',
	'source/spcldialog.cpp',
]

def getFileList(dir):
	result = []
	for file in map(lambda(x): x.replace('\\', '/'), glob(dir + '/*')):
		if path.isdir(file):
			result += getFileList(file)
		else:
			if file.endswith(".cpp") and not file in blacklist:
				result += [file]
	return result

def object(source):
	return objectDir + '/' + source.replace('.cpp', '.o')

objectDir = 'build/' + target
sourceFiles = getFileList('source')
objectFiles = map(object, sourceFiles)
objectFiles.append(objectDir + '/lunatic.res')

out = open('build/generated.make', 'w')
def write(ln): out.write(ln + '\n')

write('# Autogenerated makefile for target ' + target)
write('LDLIBS=' + linkflags)
write('CXXFLAGS=' + cxxflags)
write('OBJFILES=' + ' \\\n\t'.join(objectFiles))

write('bin/' + target + '.exe: ${OBJFILES}')
write('\t@mkdir -p bin')
write('\t${LINK.cc} -o bin/' + target + '.exe ${OBJFILES} ${LDLIBS}')

for source in sourceFiles:
	obj = object(source)
	write(obj + ': ' + source)
	write('\t@mkdir -p ' + path.split(obj)[0])
	write('\t$(COMPILE.cc) -MMD -MP -MF $@.d -o $@ ' + source)
	if path.exists(obj + '.d'):
		write('include ' + obj + '.d')

# calculate dependencies of lunatic.rc
rc = open('source/lunatic.rc', 'r')
resFiles = ''
for line in rc:
	list = re.split('\\s+', line.strip())
	filename = list[2]
	if filename.startswith('"'):
		resFiles += ' source/' + filename[1:-1]
	else:
		resFiles += ' source/' + filename
rc.close()

write(objectDir + '/lunatic.res: source/lunatic.rc' + resFiles)
write('\twindres source/lunatic.rc -O coff -o ' + objectDir + '/lunatic.res')

out.close()
